### ISSUE TITLE
Any plan to use xslt 3.0 ?

### ISSUE THREAD

**Issue by jfcjm** [essentialproject/essential_viewer#2]
xslt 3.0 defines new data types such as maps and arrays along with native functions to translate  such data type (and sequences) to json.

Use of these new types/functions would greatly facilitate both 1) mappings from xml to json in reports and 2) i18n code  compatibility with language where the quotation mark is heavily used (such as french :).

**Comment by neilwalsh** [comment]
XSLT 3.0 will be available in the next release (v6.11)

**Comment by neilwalsh** [comment]
XSLT 3.0 is now available in Essential Viewer since v6.11
